AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  getDateTime

  Sample SAM Template for Calculator

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  Calculator:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Calculator
      Description: Calculator funtion
      Role: arn:aws:iam::978889004198:role/JenkinsDemo
      CodeUri: calculator/
      Handler: calculator.lambda_handler
      Runtime: python3.8
      Events:
        DateTime:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /calculator/{choice}/{firstNumber}/{secondNumber}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CalculatorApi:
    Description: "Calculator Api"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/calculator/{choice}/{firstNumber}/{secondNumber}"
  CalculatorFunction:
    Description: "Get date time Lambda Function ARN"
    Value: !GetAtt Calculator.Arn
